#!/usr/bin/env node
/*
 * Generates en/index.html from index.html (the Turkish source of truth).
 *
 *   node build-en.mjs
 *
 * Run it after every edit to index.html. Translation lives next to the
 * Turkish copy in the source:
 *   data-tr="…" data-en="…"   element content (the inner HTML must equal data-tr)
 *   data-en-<suffix>="…"      attribute value, where <suffix> is one of
 *                             ph → placeholder, aria → aria-label, alt, href,
 *                             hreflang, content
 * The build fails loudly if an element's content no longer matches its data-tr,
 * so a stale translation can never ship silently.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(ROOT, 'index.html'), 'utf8');

const ATTR_FOR_SUFFIX = { ph: 'placeholder', aria: 'aria-label', alt: 'alt', href: 'href', hreflang: 'hreflang', content: 'content' };
const VOID = new Set(['meta', 'link', 'img', 'input', 'br', 'hr', 'source']);

/** Parses the opening tag starting at `i` (which points at '<'). Quote-aware, so '>' inside attribute values is fine. */
function parseTag(html, i) {
    const nameMatch = /^<([a-zA-Z][a-zA-Z0-9-]*)/.exec(html.slice(i, i + 40));
    if (!nameMatch) return null;
    let j = i + nameMatch[0].length;
    const attrs = [];
    while (j < html.length) {
        while (/\s/.test(html[j])) j++;
        if (html[j] === '>' || html.startsWith('/>', j)) break;
        const start = j;
        while (j < html.length && !/[\s=>]/.test(html[j])) j++;
        const name = html.slice(start, j);
        let value = null;
        if (html[j] === '=') {
            const q = html[j + 1];
            const close = html.indexOf(q, j + 2);
            value = html.slice(j + 2, close);
            j = close + 1;
        }
        attrs.push({ name, value });
    }
    const end = html.indexOf('>', j) + 1;
    return { name: nameMatch[1].toLowerCase(), attrs, start: i, end };
}

const escAttr = (v) => v.replace(/&(?![a-zA-Z#0-9]+;)/g, '&amp;').replace(/"/g, '&quot;');
// Inner HTML uses double quotes where the attribute copy had to use single ones.
const quoteTags = (s) => s.replace(/<[^>]*>/g, (t) => t.replace(/'/g, '"'));
const sameMarkup = (a, b) => quoteTags(a) === quoteTags(b);

let out = '';
let pos = 0;
let swapped = 0;

for (let i = src.indexOf('<'); i !== -1; i = src.indexOf('<', i + 1)) {
    if (src.startsWith('<!--', i)) { i = src.indexOf('-->', i); continue; }
    if (src.startsWith('<script', i) || src.startsWith('<style', i)) {
        // Copy <script>/<style> bodies verbatim; only their opening tag could carry attributes we care about (none do).
        const close = src.indexOf(src.startsWith('<script', i) ? '</script>' : '</style>', i);
        i = close;
        continue;
    }
    const tag = parseTag(src, i);
    if (!tag) continue;
    const get = (n) => tag.attrs.find((a) => a.name === n)?.value;

    const enAttrs = tag.attrs.filter((a) => a.name.startsWith('data-en-'));
    const tr = get('data-tr');
    const en = get('data-en');
    if (!enAttrs.length && en === undefined && tag.name !== 'html') continue;

    // Rebuild the opening tag with English attribute values.
    const overrides = {};
    for (const a of enAttrs) {
        const target = ATTR_FOR_SUFFIX[a.name.slice('data-en-'.length)];
        if (!target) throw new Error(`Unknown translation attribute ${a.name} on <${tag.name}>`);
        overrides[target] = a.value;
    }
    if (tag.name === 'html') overrides.lang = 'en';
    // The translation attributes have done their job; the English page ships without them.
    const attrText = tag.attrs.filter(({ name }) => !/^data-(tr|en)(-|$)/.test(name)).map(({ name, value }) => {
        const v = name in overrides ? escAttr(overrides[name]) : value;
        return v === null ? ` ${name}` : ` ${name}="${v}"`;
    }).join('');
    out += src.slice(pos, tag.start) + `<${tag.name}${attrText}>`;
    pos = tag.end;

    if (en !== undefined && !VOID.has(tag.name)) {
        const inner = src.slice(tag.end, tag.end + tr.length);
        if (!sameMarkup(inner, tr)) {
            const line = src.slice(0, tag.start).split('\n').length;
            throw new Error(`index.html:${line} <${tag.name}> content does not match its data-tr — update data-tr/data-en.\n  data-tr: ${tr}\n  content: ${inner}`);
        }
        out += en.replace(/<[^>]*>/g, (t) => t.replace(/'/g, '"'));
        pos = tag.end + tr.length;
        swapped++;
    }
    i = tag.end - 1;
}
out += src.slice(pos);

out = out.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n<!-- Generated by build-en.mjs from index.html — do not edit by hand. -->');

mkdirSync(join(ROOT, 'en'), { recursive: true });
writeFileSync(join(ROOT, 'en', 'index.html'), out);
console.log(`en/index.html written — ${swapped} text blocks translated.`);
